version: "2"
volumes:
  production-map:
services:
  db:
    image: mongo
    volumes:
        - production-map:/data/db
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      PM_DB_HOST: db  
      PM_DB_PORT: 27017
